In [71]:
import numpy as np
import sympy as sp
import scipy as sc
from math import *
from random import *

конвертация матрицы в для отправки

In [15]:
matrix = np.random.randint(-3,10,size=(2,3))
dic = {"data": matrix.tolist()}
dic

{'data': [[-3, 9, 1], [-1, -2, -3]]}

конвертация массива в матрицу

In [16]:
np.asmatrix(dic['data'])

matrix([[-3,  9,  1],
        [-1, -2, -3]])

определитель

In [21]:
matrix = np.random.randint(-3,10,size=(3,3))
np.around(np.linalg.det(matrix), 1 ), np.linalg.det(matrix)

(-105.0, -104.99999999999997)

транспонирование

In [22]:
matrix.transpose()

array([[-2,  7, -1],
       [ 3,  0, -3],
       [ 6,  0, -1]])

Ранг матрицы

In [23]:
np.linalg.matrix_rank(matrix)

3

обратная матрица

In [24]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[ 8, -5, -6],
       [-6, -5, -4],
       [ 6,  6,  7]])

In [25]:
InvA = np.around(np.linalg.inv(a), 1)
InvA

array([[ 0.1,  0. ,  0.1],
       [-0.1, -0.6, -0.5],
       [ 0. ,  0.5,  0.5]])

Сумма матриц

In [31]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

8

Умножение числа на матрицу

In [33]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[16, 10,  4,  0],
       [14,  0, 14,  0],
       [10,  8, 10, 18],
       [18, 16, 10,  4]])

Умножение матриц

In [35]:
matrix1 = np.random.randint(-9, 10, size=(2,2))
matrix2 = np.random.randint(-9, 10, size=(2,2))


matrix1,matrix2,np.dot(matrix1, matrix2)

(array([[-3,  7],
        [-8,  2]]),
 array([[-7, -1],
        [ 4,  1]]),
 array([[49, 10],
        [64, 10]]))

Генерация невырожденной матрицы

In [37]:
def generateNonsingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))

  return a

Уравнение с определителем

In [38]:
def GenerateDeterminantEquationTask():
  matrix = generateNonsingularMatrix(-9, 10, 3, 3)
  determinant = np.around(np.linalg.det(matrix))

  row_count = matrix.shape[0]
  columns_count = matrix.shape[1]

  row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
  column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
  random_elem = matrix[row_index][column_index]

  new_matrix = np.where(matrix == random_elem, "x", matrix)
  task = "Какое значение должно стоять на месте x, чтобы соблюдалось равенство?" 

  dic = {
    "task":task,
    "data": {"matrix": new_matrix.tolist(), "determinant": determinant},
    "answer": int(random_elem)}
  return dic

print(GenerateDeterminantEquationTask())

{'task': 'Какое значение должно стоять на месте x, чтобы соблюдалось равенство?', 'data': {'matrix': [['-2', 'x', '-5'], ['-8', '-8', '2'], ['6', '2', '3']], 'determinant': -248.0}, 'answer': -4}


Матричные уравнения

In [39]:
def GenerateSolveMatrixEquationTask():
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  answer = np.around(np.dot(a1, b), 3)
  task = "Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой"
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveMatrixEquationTask())

{'task': 'Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[3, 1, 9], [-4, 9, 7], [7, -5, 9]], 'B': [[-2, -9, -2], [3, -1, -8], [-1, 0, 5]]}, 'answer': [[-7.0, -21.5, -3.7], [-4.8, -15.8, -3.6], [2.6, 7.9, 1.4]]}


In [40]:
def GenerateSolveDoubleMatrixEquationTask():
  task = "Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой"
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  c = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  b1 = np.linalg.inv(b)
  x = np.dot(a1,c)
  answer = np.around(np.dot(x, b1), 3)
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist(), "C": c.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveDoubleMatrixEquationTask())

{'task': 'Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[-4, -3, -9], [-9, 1, -1], [-4, 4, 1]], 'B': [[9, 5, 7], [-6, -8, 0], [9, 4, 6]], 'C': [[9, -9, 0], [4, 6, -4], [1, -7, 0]]}, 'answer': [[-0.1, 0.2, 0.2], [-1.4, 0.5, 1.7], [1.5, -0.3, -1.8]]}


Ранг матрицы

In [41]:
def GenerateFindMatrixRankTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]
  task = "Определите ранг матрицы"

  if switch == 0:
    matrix = np.random.randint(-9, 10, size=(3,3))
    answer = np.linalg.matrix_rank(matrix)
      
  else:
    matrix = np.random.randint(-9, 10, size=(2,3))
    factor1, factor2 = 0, 0
    while factor1 == 0 or factor2 == 0:
        factor1 = np.random.randint(-3, 4, size=(1,1))[0][0]
        factor2 = np.random.randint(-3, 4, size=(1,1))[0][0]

    matrix = np.vstack([matrix, factor1 * matrix[0] + factor2*matrix[1]])
    np.random.shuffle(matrix)
    answer = np.linalg.matrix_rank(matrix)
  
  dic = {
  "task":task,
  "data": matrix.tolist(),
  "answer": answer.item()}
  return dic

print(GenerateFindMatrixRankTask())

{'task': 'Определите ранг матрицы', 'data': [[-4, 3, -2], [-2, -1, 6], [-5, 5, -6]], 'answer': 2}


Система линейных уравнений

In [42]:
def generateSLU(x_count, equation_count, min_value, max_value):
  a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

  b = np.random.randint(min_value, max_value, size=(x_count, 1))
  x = np.random.randint(1, size=(x_count, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

    b = np.random.randint(min_value, max_value, size=(x_count, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

print(generateSLU(3,3,-5, 21))

(array([[ 8,  9, -3],
       [ 4, 18,  6],
       [-2,  7,  7]]), array([[13],
       [18],
       [ 7]]), array([[ 2.8       ],
       [-0.33333333],
       [ 2.13333333]]))


In [ ]:
def GenerateSolveLinearEquationTask():
  a, b, x = generateSLU(3, 3, -5, 21)
  first_equation = f"{a[0][0]}*x + {a[0][1]}*y + {a[0][2]}*z = {b[0].item()}"
  second_equation = f"{a[1][0]}*x + {a[1][1]}*y + {a[1][2]}*z = {b[1].item()}"
  third_equation = f"{a[2][0]}*x + {a[2][1]}*y + {a[2][2]}*z = {b[2].item()}"
  task = "Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой"  
  answer = np.around(x,1).tolist()
  dic = {
  "task":task,
  "data": {"first_equation": first_equation, "second_equation": second_equation, "third_equation" : third_equation},
  "answer": answer}
  return dic

print(GenerateSolveLinearEquationTask())

{'task': 'Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой', 'data': {'first_equation': '7*x + 3*y + 15*z = 9', 'second_equation': '8*x + 13*y + 20*z = 20', 'third_equation': '-4*x + -2*y + 13*z = 13'}, 'answer': [[-0.864], [0.761], [0.851]]}


Скалярное произведение векторов

In [43]:
def GenerateScalarVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))[0]
  b = np.random.randint(-20, 21, size=(1,3))[0]
  task = "Вычислите скалярное произведение векторов A и B."
  answer = a @ b
  dic = {
    "task": task,
    "data": {"A": a.tolist(), "B": b.tolist()},
    "answer": answer}
  return dic

print(GenerateScalarVectorMultiplicationTask())

{'task': 'Вычислите скалярное произведение векторов A и B.', 'data': {'A': [2, 20, -20], 'B': [-15, 1, -4]}, 'answer': 70}


Векторное произведение векторов

In [44]:
def GenerateVectorVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b])
  xy = combined[:2, :2]
  yz = combined[:2, 1:3]
  xz = combined[:2, [0, 2]]
  answer = np.array([int(np.linalg.det(yz)), -1 * int(np.linalg.det(xz)), int(np.linalg.det(xy))])
  task = "Вычислите векторное произведение векторов А и В."
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0]},
    "answer": answer.tolist()}
  return dic

print(GenerateVectorVectorMultiplicationTask())


{'task': 'Вычислите векторное произведение векторов А и В.', 'data': {'A': [-15, -9, 9], 'B': [-16, 20, -14]}, 'answer': [-54, -353, -444]}


Длина Вектора

In [73]:

def GenerateVectorVectorMultiplicationModuleTask():
  temp = GenerateVectorVectorMultiplicationTask()
  a = temp["data"]["A"]
  b = temp["data"]["B"]
  vector = np.array(temp["answer"])
  answer = np.around(sqrt(vector[0]**2 + vector[1]**2 + vector[2]**2 ), 1)
  task = "Вычислите длинну вектора, полученную в результате векторного произведения A и B"
  dic = {
    "task": task,
    "data": {"A": a, "B": b},
    "answer": answer.tolist()}
  return dic


print(GenerateVectorVectorMultiplicationModuleTask())

{'task': 'Вычислите длинну вектора, полученную в результате векторного произведения A и B', 'data': {'A': [-14, 12, 3], 'B': [19, 11, 0]}, 'answer': 387.6}


Смешанное произведение векторов

In [ ]:
def GenerateMixedVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))
  c = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b, c])
  answer = np.around(np.linalg.det(combined))
  task = "Вычислите смешанное произведение векторов A, B и C"
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0], "C": c.tolist()[0]},
    "answer": answer}
  return dic

print(GenerateMixedVectorMultiplicationTask())


{'task': 'Вычислите смешанное произведение векторов A, B и C', 'data': {'A': [10, 11, -14], 'B': [-10, 8, 0], 'C': [14, 7, -18]}, 'answer': -872.0}


Коллинеарность векторов

In [ ]:
def GenerateIsCollinearVectorsTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]

  if switch == 0:
    a = np.random.randint(-20, 21, size=(1,3))[0]
    b = np.random.randint(-20, 21, size=(1,3))[0]
  else:
    fraction = np.random.randint(-3, 5, size=(1,1))[0][0]
    a = np.random.randint(-20, 21, size=(1,3))[0]
    b = fraction * a

  first,second,third = a[0]/b[0],a[1]/b[1],a[2]/b[2]

  task = "Являются ли вектор A и вектор B коллинеарными? В ответе указать Да или Нет."
  ansver = "Да" if np.equal(first,second) and np.equal(first,third) else "Нет"

  dic = {
    "task": task,
    "data": {"A": a.tolist(), "B": b.tolist()},
    "ansver": ansver}

  return dic

print(GenerateIsCollinearVectorsTask())

[-18  18  -1] [ 54 -54   3]
{'task': 'Являются ли вектор A и вектор B коллинеарными? В ответе указать Да или Нет.', 'data': {'A': [-18, 18, -1], 'B': [54, -54, 3]}, 'ansver': 'Да'}


Компланарность векторов

In [61]:
def generateSingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) != 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  return a

print(generateSingularMatrix(1, 10, 3, 3))

[[8 3 1]
 [8 9 3]
 [6 9 3]]


In [63]:
def GenerateIsComplanarVectorsTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]

  if switch == 0:
    data = generateNonsingularMatrix(-20, 21, 3, 3)
  else:
    data = generateSingularMatrix(-20, 21, 3, 3)
  
  task = "Являются ли векторы A B и C компланарными? В ответе указать Да или Нет."
  answer = "Да" if switch != 0 else "Нет"

  dic = {
    "task": task,
    "data": {"A": data[0].tolist(), "B":data[1].tolist(), "C": data[2].tolist()},
    "answer": answer}
  
  return dic

print(GenerateIsComplanarVectorsTask())
    

{'task': 'Являются ли векторы A B и C компланарными? В ответе указать Да или Нет.', 'data': {'A': [15, -19, 18], 'B': [4, -5, -19], 'C': [-18, -3, 6]}, 'answer': 'Нет'}


Поиск уравнения паралельного вектора, проходящего через точку.

In [75]:
def GenerateFindParalelLineEquationTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    A = sp.Point(A1,A2)
    B1,B2 = randint(-9, 9),randint(-9, 9)
    L1 = sp.Line((0, 0), (B1, B2))

    L2 = L1.parallel_line(A)
    task = f"Известно, что прямая  L  проходит через начало координат и точку  B({B1},{B2}). Записать уравнение прямой, проходящей через точку  A({A1},{A2})  параллельно прямой  L"
    answer = L2.equation()

    dic = {
        "task": task,
        "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в таске.
        "answer": answer}
    
    return dic

print(GenerateFindParalelLineEquationTask())

{'task': 'Известно, что прямая  L  проходит через начало координат и точку  B(-7,-2). Записать уравнение прямой, проходящей через точку  A(-4,-5)  параллельно прямой  L', 'data': {}, 'answer': 2*x - 7*y - 27}
