In [113]:
import numpy as np
import sympy as sp
import scipy as sc
from math import *
from random import *

конвертация матрицы в для отправки

In [114]:
matrix = np.random.randint(-3,10,size=(2,3))
dic = {"data": matrix.tolist()}
dic

{'data': [[5, 5, 3], [9, 0, 6]]}

конвертация массива в матрицу

In [115]:
np.asmatrix(dic['data'])

matrix([[5, 5, 3],
        [9, 0, 6]])

определитель

In [116]:
matrix = np.random.randint(-3,10,size=(3,3))
np.around(np.linalg.det(matrix), 1 ), np.linalg.det(matrix)

(-729.0, -729.0000000000001)

транспонирование

In [117]:
matrix.transpose()

array([[ 7,  8,  0],
       [ 9,  1,  6],
       [-3,  0,  9]])

Ранг матрицы

In [118]:
np.linalg.matrix_rank(matrix)

3

обратная матрица

In [119]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[-2, -4,  2],
       [ 6,  3, -3],
       [-1, -9, -9]])

In [120]:
InvA = np.around(np.linalg.inv(a), 1)
InvA

array([[ 0.2,  0.2, -0. ],
       [-0.3, -0.1, -0. ],
       [ 0.2,  0.1, -0.1]])

Сумма матриц

In [121]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

8

Умножение числа на матрицу

In [122]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[12,  0,  6,  3],
       [ 3,  6,  9, 18],
       [ 9,  9, 18,  6],
       [15, 12,  3, 27]])

Умножение матриц

In [123]:
matrix1 = np.random.randint(-9, 10, size=(2,2))
matrix2 = np.random.randint(-9, 10, size=(2,2))


matrix1,matrix2,np.dot(matrix1, matrix2)

(array([[ 1,  4],
        [-5, -6]]),
 array([[ 0,  0],
        [-3, -2]]),
 array([[-12,  -8],
        [ 18,  12]]))

Генерация невырожденной матрицы

In [124]:
def generateNonsingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))

  return a

Уравнение с определителем

In [125]:
def GenerateDeterminantEquationTask():
  matrix = generateNonsingularMatrix(-9, 10, 3, 3)
  determinant = np.around(np.linalg.det(matrix))

  row_count = matrix.shape[0]
  columns_count = matrix.shape[1]

  row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
  column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
  random_elem = matrix[row_index][column_index]

  new_matrix = np.where(matrix == random_elem, "x", matrix)
  task = "Какое значение должно стоять на месте x, чтобы соблюдалось равенство?" 

  dic = {
    "task":task,
    "data": {"matrix": new_matrix.tolist(), "determinant": determinant},
    "answer": int(random_elem)}
  return dic

print(GenerateDeterminantEquationTask())

{'task': 'Какое значение должно стоять на месте x, чтобы соблюдалось равенство?', 'data': {'matrix': [['x', '-3', '6'], ['-4', '-6', 'x'], ['9', '9', '1']], 'determinant': 96.0}, 'answer': 0}


Матричные уравнения

In [126]:
def GenerateSolveMatrixEquationTask():
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  answer = np.around(np.dot(a1, b), 3)
  task = "Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой"
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveMatrixEquationTask())

{'task': 'Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[-3, 5, -3], [3, -8, -8], [3, 1, -4]], 'B': [[9, 8, 5], [8, 9, 0], [3, -2, 7]]}, 'answer': [[-1.165, -2.303, 0.95], [0.149, -0.609, 1.115], [-1.586, -1.379, -0.759]]}


In [127]:
def GenerateSolveDoubleMatrixEquationTask():
  task = "Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой"
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  c = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  b1 = np.linalg.inv(b)
  x = np.dot(a1,c)
  answer = np.around(np.dot(x, b1), 3)
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist(), "C": c.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveDoubleMatrixEquationTask())

{'task': 'Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[-6, 7, 8], [-4, -7, -6], [-6, 3, 7]], 'B': [[-1, -4, -3], [-5, 2, -3], [-4, -3, -2]], 'C': [[-2, -9, -9], [-1, -9, -3], [-2, 6, 4]]}, 'answer': [[-0.761, 0.038, 0.07], [1.703, 0.068, -0.513], [-1.672, 0.026, 0.396]]}


Ранг матрицы

In [128]:
def GenerateFindMatrixRankTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]
  task = "Определите ранг матрицы"

  if switch == 0:
    matrix = np.random.randint(-9, 10, size=(3,3))
    answer = np.linalg.matrix_rank(matrix)
      
  else:
    matrix = np.random.randint(-9, 10, size=(2,3))
    factor1, factor2 = 0, 0
    while factor1 == 0 or factor2 == 0:
        factor1 = np.random.randint(-3, 4, size=(1,1))[0][0]
        factor2 = np.random.randint(-3, 4, size=(1,1))[0][0]

    matrix = np.vstack([matrix, factor1 * matrix[0] + factor2*matrix[1]])
    np.random.shuffle(matrix)
    answer = np.linalg.matrix_rank(matrix)
  
  dic = {
  "task":task,
  "data": matrix.tolist(),
  "answer": answer.item()}
  return dic

print(GenerateFindMatrixRankTask())

{'task': 'Определите ранг матрицы', 'data': [[-6, 3, 5], [36, -27, -25], [9, -9, -5]], 'answer': 2}


Система линейных уравнений

In [129]:
def generateSLU(x_count, equation_count, min_value, max_value):
  a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

  b = np.random.randint(min_value, max_value, size=(x_count, 1))
  x = np.random.randint(1, size=(x_count, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

    b = np.random.randint(min_value, max_value, size=(x_count, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

print(generateSLU(3,3,-5, 21))

(array([[ 1, 12,  6],
       [-3, 12, -5],
       [-5, 15, -1]]), array([[ 6],
       [ 9],
       [17]]), array([[-2.27338129],
       [ 0.41247002],
       [ 0.55395683]]))


In [130]:
def GenerateSolveLinearEquationTask():
  a, b, x = generateSLU(3, 3, -5, 21)
  first_equation = f"{a[0][0]}*x + {a[0][1]}*y + {a[0][2]}*z = {b[0].item()}"
  second_equation = f"{a[1][0]}*x + {a[1][1]}*y + {a[1][2]}*z = {b[1].item()}"
  third_equation = f"{a[2][0]}*x + {a[2][1]}*y + {a[2][2]}*z = {b[2].item()}"
  task = "Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой"  
  answer = np.around(x,1).tolist()
  dic = {
  "task":task,
  "data": {"first_equation": first_equation, "second_equation": second_equation, "third_equation" : third_equation},
  "answer": answer}
  return dic

print(GenerateSolveLinearEquationTask())

{'task': 'Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой', 'data': {'first_equation': '3*x + -1*y + 10*z = 5', 'second_equation': '17*x + -5*y + 13*z = 2', 'third_equation': '14*x + 12*y + 13*z = 20'}, 'answer': [[-0.0], [1.1], [0.6]]}


Скалярное произведение векторов

In [131]:
def GenerateScalarVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))[0]
  b = np.random.randint(-20, 21, size=(1,3))[0]
  task = "Вычислите скалярное произведение векторов A и B."
  answer = a @ b
  dic = {
    "task": task,
    "data": {"A": a.tolist(), "B": b.tolist()},
    "answer": answer}
  return dic

print(GenerateScalarVectorMultiplicationTask())

{'task': 'Вычислите скалярное произведение векторов A и B.', 'data': {'A': [14, -10, -17], 'B': [-4, -3, 2]}, 'answer': -60}


Векторное произведение векторов

In [132]:
def GenerateVectorVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b])
  xy = combined[:2, :2]
  yz = combined[:2, 1:3]
  xz = combined[:2, [0, 2]]
  answer = np.array([int(np.linalg.det(yz)), -1 * int(np.linalg.det(xz)), int(np.linalg.det(xy))])
  task = "Вычислите векторное произведение векторов А и В."
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0]},
    "answer": answer.tolist()}
  return dic

print(GenerateVectorVectorMultiplicationTask())


{'task': 'Вычислите векторное произведение векторов А и В.', 'data': {'A': [-13, -9, -14], 'B': [1, -3, 18]}, 'answer': [-204, 219, 47]}


Длина Вектора

In [133]:

def GenerateVectorVectorMultiplicationModuleTask():
  temp = GenerateVectorVectorMultiplicationTask()
  a = temp["data"]["A"]
  b = temp["data"]["B"]
  vector = np.array(temp["answer"])
  answer = np.around(sqrt(vector[0]**2 + vector[1]**2 + vector[2]**2 ), 1)
  task = "Вычислите длинну вектора, полученную в результате векторного произведения A и B"
  dic = {
    "task": task,
    "data": {"A": a, "B": b},
    "answer": answer.tolist()}
  return dic


print(GenerateVectorVectorMultiplicationModuleTask())

{'task': 'Вычислите длинну вектора, полученную в результате векторного произведения A и B', 'data': {'A': [-1, 16, -10], 'B': [2, 0, -1]}, 'answer': 41.1}


Смешанное произведение векторов

In [134]:
def GenerateMixedVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))
  c = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b, c])
  answer = np.around(np.linalg.det(combined))
  task = "Вычислите смешанное произведение векторов A, B и C"
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0], "C": c.tolist()[0]},
    "answer": answer}
  return dic

print(GenerateMixedVectorMultiplicationTask())


{'task': 'Вычислите смешанное произведение векторов A, B и C', 'data': {'A': [15, 16, -8], 'B': [6, -6, 20], 'C': [14, 12, -11]}, 'answer': 1678.0}


Коллинеарность векторов

In [135]:
def GenerateIsCollinearVectorsTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]

  if switch == 0:
    a = np.random.randint(-20, 21, size=(1,3))[0]
    b = np.random.randint(-20, 21, size=(1,3))[0]
  else:
    fraction = np.random.randint(-3, 5, size=(1,1))[0][0]
    a = np.random.randint(-20, 21, size=(1,3))[0]
    b = fraction * a

  first,second,third = a[0]/b[0],a[1]/b[1],a[2]/b[2]

  task = "Являются ли вектор A и вектор B коллинеарными? В ответе указать Да или Нет."
  ansver = "Да" if np.equal(first,second) and np.equal(first,third) else "Нет"

  dic = {
    "task": task,
    "data": {"A": a.tolist(), "B": b.tolist()},
    "ansver": ansver}

  return dic

print(GenerateIsCollinearVectorsTask())

{'task': 'Являются ли вектор A и вектор B коллинеарными? В ответе указать Да или Нет.', 'data': {'A': [-1, -16, 2], 'B': [-4, -64, 8]}, 'ansver': 'Да'}


Компланарность векторов

In [136]:
def generateSingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) != 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  return a

print(generateSingularMatrix(1, 10, 3, 3))

[[6 3 3]
 [5 3 4]
 [5 3 4]]


In [137]:
def GenerateIsComplanarVectorsTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]

  if switch == 0:
    data = generateNonsingularMatrix(-20, 21, 3, 3)
  else:
    data = generateSingularMatrix(-20, 21, 3, 3)
  
  task = "Являются ли векторы A B и C компланарными? В ответе указать Да или Нет."
  answer = "Да" if switch != 0 else "Нет"

  dic = {
    "task": task,
    "data": {"A": data[0].tolist(), "B":data[1].tolist(), "C": data[2].tolist()},
    "answer": answer}
  
  return dic

print(GenerateIsComplanarVectorsTask())
    

{'task': 'Являются ли векторы A B и C компланарными? В ответе указать Да или Нет.', 'data': {'A': [0, -7, -18], 'B': [-20, -13, -16], 'C': [-2, 4, 18]}, 'answer': 'Нет'}


Поиск уравнения прямой

In [138]:
def GenerateFindLineEquationByPointsTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    B1,B2 = randint(-9, 9),randint(-9, 9)

    A, B = sp.Point(A1, A2), sp.Point(B1, B2)
    L = sp.Line(A, B)

    task = f"Составить уравнение прямой, проходящей через две точки:  A({A1},{A2})  и  B({B1},{B2})"
    answer = L.equation()

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}
    return dic

print(GenerateFindLineEquationByPointsTask())

{'task': 'Составить уравнение прямой, проходящей через две точки:  A(7,-6)  и  B(-2,3)', 'data': {}, 'answer': -9*x - 9*y + 9}


Поиск уравнения паралельного вектора, проходящего через точку.

In [139]:
def GenerateFindParalelLineEquationTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    A = sp.Point(A1,A2)
    B1,B2 = randint(-9, 9),randint(-9, 9)
    L1 = sp.Line((0, 0), (B1, B2))

    L2 = L1.parallel_line(A)
    task = f"Известно, что прямая  L  проходит через начало координат и точку  B({B1},{B2}). Записать уравнение прямой, проходящей через точку  A({A1},{A2})  параллельно прямой  L"
    answer = L2.equation()

    dic = {
        "task": task,
        "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в таске.
        "answer": answer}
    
    return dic

print(GenerateFindParalelLineEquationTask())

{'task': 'Известно, что прямая  L  проходит через начало координат и точку  B(4,-3). Записать уравнение прямой, проходящей через точку  A(-3,2)  параллельно прямой  L', 'data': {}, 'answer': 3*x + 4*y + 1}


In [140]:
def GenerateFindParalelLineEquationByPointsTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    B1,B2 = randint(-9, 9),randint(-9, 9)
    C1,C2 = randint(-9, 9),randint(-9, 9)
    A = sp.Point(A1,A2)
    L1 = sp.Line((B1, B2), (C1, C2))

    L2 = L1.parallel_line(A)
    task = f"Составить уравнение прямой, проходящей через точку А({A1},{A2}), параллельную прямой BC, если B({B1},{B2}), C({C1},{C2})"
    answer = L2.equation()

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}

    return dic
    
print(GenerateFindParalelLineEquationByPointsTask())

{'task': 'Составить уравнение прямой, проходящей через точку А(-4,9), параллельную прямой BC, если B(9,-8), C(7,9)', 'data': {}, 'answer': -17*x - 2*y - 50}


Поиск точки пересечения прямых

In [141]:
def GenerateFindCrossPointOfTwoLinesTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    B1,B2 = randint(-9, 9),randint(-9, 9)
    C1,C2 = randint(-9, 9),randint(-9, 9)
    D1,D2 = randint(-9, 9),randint(-9, 9)

    L1 = sp.Line((A1, A2), (B1, B2))
    L2 = sp.Line((C1, C2), (D1, D2))

    task = f"Найти точку пересечения прямых L1 и L2, если известно, что прямая L1 проходит через точки А({A1},{A2}) и B({B1},{B2}), а прямая L2 проходит через точки C({C1},{C2}) и D({D1},{D2})"
    answer = list(L1.intersection(L2)[0].coordinates)

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}
    return dic


print(GenerateFindCrossPointOfTwoLinesTask())

{'task': 'Найти точку пересечения прямых L1 и L2, если известно, что прямая L1 проходит через точки А(0,7) и B(-9,-8), а прямая L2 проходит через точки C(3,-1) и D(-8,9)', 'data': {}, 'answer': [-174/85, 61/17]}


Поиск расстояния от точки до прямой

In [142]:
def GenerateFindDicstanceFromLineToPointTask():
    A1,A2 = randint(-9, 9),randint(-9, 9)
    B1,B2 = randint(-9, 9),randint(-9, 9)
    C1,C2 = randint(-9, 9),randint(-9, 9)

    C = sp.Point(C1, C2)
    L1 = sp.Line((A1, A2), (B1, B2))

    task = f"Известно, что прямая L проходит через точки A({A1},{A2}) и B({B1},{B2}). Из точки C({C1},{C2}) на прямую L опущен перпендикуляр, который касается её в точке D. Определить длину отрезка CD. Пример формы ответа: 3*sqrt(26)/13"
    answer = L1.perpendicular_segment(C).length

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}
    return dic

print(GenerateFindDicstanceFromLineToPointTask())

{'task': 'Известно, что прямая L проходит через точки A(0,9) и B(8,-2). Из точки C(8,1) на прямую L опущен перпендикуляр, который касается её в точке D. Определить длину отрезка CD. Пример формы ответа: 3*sqrt(26)/13', 'data': {}, 'answer': 24*sqrt(185)/185}


Уравнение плоскости по трем точкам

In [143]:
def GenerateFindPlaneEquationByThreePointsTask():
    A1,A2,A3 = randint(-9, 9),randint(-9, 9),randint(-9, 9)
    B1,B2,B3 = randint(-9, 9),randint(-9, 9),randint(-9, 9)
    C1,C2,C3 = randint(-9, 9),randint(-9, 9),randint(-9, 9)

    alpha = sp.Plane(sp.Point3D(A1, A2, A3), sp.Point3D(B1, B2, B3), sp.Point3D(C1, C2, C3))

    task = f"Записать уравнение плоскости, проходящей через точки A({A1},{A2},{A3}), B({B1},{B2},{B3}), C({C1},{C2},{C3}). Пример формы записи ответа: 38*x - 136*y - 126*z - 574"
    answer = alpha.equation()

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}
    return dic

print(GenerateFindPlaneEquationByThreePointsTask())

{'task': 'Записать уравнение плоскости, проходящей через точки A(4,5,8), B(3,0,-2), C(-7,9,-2). Пример формы записи ответа: 38*x - 136*y - 126*z - 574', 'data': {}, 'answer': 90*x + 100*y - 59*z - 388}


Уравнение прямой по нормальному вектору и точке

In [144]:
def GenerateFindPlaneEquationByPointAndNormalVector():
    A1,A2,A3 = randint(-9, 9),randint(-9, 9),randint(-9, 9)
    B1,B2,B3 = randint(-9, 9),randint(-9, 9),randint(-9, 9)

    alpha = sp.Plane(sp.Point3D(A1, A2, A3), normal_vector =(B1, B2, B3))

    task = f"Записать уравнение плоскости a, которая проходит через точку M({A1},{A2},{A3}) и перпендикулярна вектору n =({B1},{B2},{B3}). Пример записи ответа: -3*x - 8*y - 8*z + 85"
    answer = alpha.equation()

    dic = {
    "task": task,
    "data": {}, #Нужно ли тут что - то на фронт возвращать? все данные уже в задаче.
    "answer": answer}
    return dic

print(GenerateFindPlaneEquationByPointAndNormalVector())

{'task': 'Записать уравнение плоскости a, которая проходит через точку M(1,2,-3) и перпендикулярна вектору n =(-8,2,-2). Пример записи ответа: -3*x - 8*y - 8*z + 85', 'data': {}, 'answer': -8*x + 2*y - 2*z - 2}
