In [2]:
import numpy as np
import sympy as sp
import scipy as sci

In [3]:
matrix_size = 3
matrix = np.random.randint(10, size=(matrix_size, matrix_size))
matrix

array([[2, 4, 0],
       [7, 0, 6],
       [8, 6, 9]])

конвертация матрицы в для отправки

In [4]:
dic = {"data": matrix.tolist()}
dic

{'data': [[2, 4, 0], [7, 0, 6], [8, 6, 9]]}

конвертация массива в матрицу

In [5]:
np.asmatrix(dic['data'])

matrix([[2, 4, 0],
        [7, 0, 6],
        [8, 6, 9]])

размер матрицы

In [6]:
matrix.shape == (matrix_size, matrix_size)

True

определитель

In [7]:
np.around(np.linalg.det(matrix), ), np.linalg.det(matrix)

(-132.0, -131.99999999999997)

транспонирование

In [8]:
matrix.transpose()

array([[2, 7, 8],
       [4, 0, 6],
       [0, 6, 9]])

Ранг матрицы

In [9]:
np.linalg.matrix_rank(matrix)

3

СЛУ

In [10]:
def generate_SLU():
  a = np.random.randint(-9, 10, size=(3, 3))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(-9, 10, size=(3,3))

  b = np.random.randint(1,10, size=(3, 1))
  x = np.random.randint(10, size=(3, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(-9, 10, size=(3, 3))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(-9, 10, size=(3,3))

    b = np.random.randint(1,10, size=(3, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

In [17]:
%time
a,b,x = generate_SLU()

print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Решение системы:\n", x)
print("Решение системы:\n", np.around(x, 3))

print(a.dot(x) == b)

CPU times: total: 0 ns
Wall time: 0 ns
Матрица A:
 [[-3 -9 -1]
 [-7 -9  0]
 [-4  6  0]]
Вектор b:
 [[8]
 [5]
 [4]]
Решение системы:
 [[-0.84615385]
 [ 0.1025641 ]
 [-6.38461538]]
Решение системы:
 [[-0.846]
 [ 0.103]
 [-6.385]]
[[ True]
 [ True]
 [ True]]
CPU times: total: 0 ns
Wall time: 0 ns


обратная матрица

In [124]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[-2,  8,  0],
       [ 9, -1,  9],
       [-9, -2, -5]])

In [125]:
InvA = np.around(np.linalg.inv(a), 3)
InvA

array([[-0.069, -0.12 , -0.216],
       [ 0.108, -0.03 , -0.054],
       [ 0.081,  0.228,  0.21 ]])

Сумма матриц

In [126]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

3

Умножение числа на матрицу

In [127]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[36, 30,  0,  0],
       [24,  0,  6,  6],
       [48, 18, 36, 36],
       [ 6, 24,  6, 24]])