In [1]:
import numpy as np
import sympy as sp
import scipy as sci

In [2]:
matrix_size = 3
matrix = np.random.randint(10, size=(matrix_size, matrix_size))
matrix

array([[2, 8, 5],
       [8, 1, 2],
       [9, 1, 3]])

конвертация матрицы в для отправки

In [3]:
dic = {"data": matrix.tolist()}
dic

{'data': [[2, 8, 5], [8, 1, 2], [9, 1, 3]]}

конвертация массива в матрицу

In [4]:
np.asmatrix(dic['data'])

matrix([[2, 8, 5],
        [8, 1, 2],
        [9, 1, 3]])

размер матрицы

In [5]:
matrix.shape == (matrix_size, matrix_size)

True

определитель

In [6]:
np.around(np.linalg.det(matrix), ), np.linalg.det(matrix)

(-51.0, -51.00000000000002)

транспонирование

In [7]:
matrix.transpose()

array([[2, 8, 9],
       [8, 1, 1],
       [5, 2, 3]])

Ранг матрицы

In [8]:
np.linalg.matrix_rank(matrix)

3

СЛУ

In [9]:
def generate_SLU():
  a = np.random.randint(-9, 10, size=(3, 3))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(-9, 10, size=(3,3))

  b = np.random.randint(1,10, size=(3, 1))
  x = np.random.randint(10, size=(3, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(-9, 10, size=(3, 3))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(-9, 10, size=(3,3))

    b = np.random.randint(1,10, size=(3, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

In [10]:
%time
a,b,x = generate_SLU()

print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Решение системы:\n", x)
print("Решение системы:\n", np.around(x, 3))

print(a.dot(x) == b)

CPU times: total: 0 ns
Wall time: 0 ns
Матрица A:
 [[ 2  3 -3]
 [-8 -1  5]
 [-1  9  9]]
Вектор b:
 [[2]
 [8]
 [8]]
Решение системы:
 [[-1.42307692]
 [ 1.17307692]
 [-0.44230769]]
Решение системы:
 [[-1.423]
 [ 1.173]
 [-0.442]]
[[ True]
 [ True]
 [ True]]


обратная матрица

In [11]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[-4,  1, -8],
       [-3,  4, -5],
       [ 2, -4,  7]])

In [12]:
InvA = np.around(np.linalg.inv(a), 3)
InvA

array([[-0.151, -0.472, -0.509],
       [-0.208,  0.226, -0.075],
       [-0.075,  0.264,  0.245]])

Сумма матриц

In [13]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

0

Умножение числа на матрицу

In [14]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[ 6, 30, 36, 12],
       [42,  0, 48,  6],
       [30, 42, 36, 36],
       [ 0, 42, 24,  6]])

Умножение матриц

In [15]:
matrix1 = np.random.randint(-9, 10, size=(2,2))
matrix2 = np.random.randint(-9, 10, size=(2,2))


matrix1,matrix2,np.dot(matrix1, matrix2)

(array([[ 1, -5],
        [-2,  0]]),
 array([[ 8, -3],
        [-9, -9]]),
 array([[ 53,  42],
        [-16,   6]]))

Генерация невырожденной матрицы

In [16]:
def generateNonsingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))

  return a

Уравнение с определителем

In [17]:
matrix = generateNonsingularMatrix(-9, 10, 3, 3)
determinant = np.around(np.linalg.det(matrix))

row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
random_elem = matrix[row_index][column_index]

new_matrix = np.where(matrix == random_elem, "x", matrix)

new_matrix, determinant, random_elem

(array([['3', '9', 'x'],
        ['4', '-2', '5'],
        ['8', '5', '5']], dtype='<U11'),
 -105.0,
 -5)

Ранг матрицы

In [40]:
switch = np.random.randint(0, 2, size=(1,1))[0][0]
if switch == 0:
    matrix = np.random.randint(-9, 10, size=(3,3))

    print(matrix, np.linalg.matrix_rank(matrix))
else:
    matrix = np.random.randint(-9, 10, size=(2,3))
    factor = 0
    while factor == 0:
        factor = np.random.randint(-3, 4, size=(1,1))[0][0]

    matrix = np.vstack([matrix, matrix[0] + factor*matrix[1]])

    print(matrix, factor, np.linalg.matrix_rank(matrix))

[[ 0 -6  2]
 [-7 -5  5]
 [ 1 -4 -8]] 3
