In [26]:
import numpy as np
import sympy as sp
import scipy as sci
from math import *

конвертация матрицы в для отправки

In [3]:
dic = {"data": matrix.tolist()}
dic

{'data': [[9, 6, 3], [2, 3, 6], [8, 3, 1]]}

конвертация массива в матрицу

In [4]:
np.asmatrix(dic['data'])

matrix([[9, 6, 3],
        [2, 3, 6],
        [8, 3, 1]])

размер матрицы

In [5]:
matrix.shape == (matrix_size, matrix_size)

True

определитель

In [6]:
np.around(np.linalg.det(matrix), ), np.linalg.det(matrix)

(87.0, 87.0)

транспонирование

In [7]:
matrix.transpose()

array([[9, 2, 8],
       [6, 3, 3],
       [3, 6, 1]])

Ранг матрицы

In [8]:
np.linalg.matrix_rank(matrix)

3

обратная матрица

In [11]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[-7, -5, -4],
       [ 5, -2, -8],
       [-9, -5,  6]])

In [12]:
InvA = np.around(np.linalg.inv(a), 3)
InvA

array([[-0.16 ,  0.153,  0.098],
       [ 0.129, -0.239, -0.233],
       [-0.132,  0.031,  0.12 ]])

Сумма матриц

In [13]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

1

Умножение числа на матрицу

In [14]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[48, 40, 64,  8],
       [32, 72, 16, 40],
       [16, 72, 72, 72],
       [32, 16, 16, 48]])

Умножение матриц

In [15]:
matrix1 = np.random.randint(-9, 10, size=(2,2))
matrix2 = np.random.randint(-9, 10, size=(2,2))


matrix1,matrix2,np.dot(matrix1, matrix2)

(array([[-3,  4],
        [-3,  1]]),
 array([[-4,  0],
        [-4,  2]]),
 array([[-4,  8],
        [ 8,  2]]))

Генерация невырожденной матрицы

In [16]:
def generateNonsingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))

  return a

Уравнение с определителем

In [99]:
def GenerateDeterminantEquationTask():
  matrix = generateNonsingularMatrix(-9, 10, 3, 3)
  determinant = np.around(np.linalg.det(matrix))

  row_count = matrix.shape[0]
  columns_count = matrix.shape[1]

  row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
  column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
  random_elem = matrix[row_index][column_index]

  new_matrix = np.where(matrix == random_elem, "x", matrix)
  task = "Какое значение должно стоять на месте x, чтобы соблюдалось равенство?" #Сделать запрос к бд

  dic = {
    "task":task,
    "data": {"matrix": new_matrix.tolist(), "determinant": determinant},
    "answer": int(random_elem)}
  return dic

print(GenerateDeterminantEquationTask())

{'task': 'Какое значение должно стоять на месте x, чтобы соблюдалось равенство?', 'data': {'matrix': [['-5', 'x', '3'], ['-5', '-9', '5'], ['-3', 'x', '4']], 'determinant': 69.0}, 'answer': -2}


Матричные уравнения

In [80]:
def GenerateSolveMatrixEquationTask():
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  answer = np.around(np.dot(a1, b), 3)
  task = "Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой"
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveMatrixEquationTask())

{'task': 'Решите уравнение вида A*X = B. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[2, -5, -8], [2, 5, -8], [-3, 9, -5]], 'B': [[2, 8, 3], [-3, 5, 3], [-8, 0, -2]]}, 'answer': [[0.75, 0.321, 0.912], [-0.5, -0.3, 0.0], [0.25, -0.732, -0.147]]}


In [79]:
def GenerateSolveDoubleMatrixEquationTask():
  task = "Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой"
  a = generateNonsingularMatrix(-9, 10, 3, 3)
  b = generateNonsingularMatrix(-9, 10, 3, 3)
  c = generateNonsingularMatrix(-9, 10, 3, 3)
  a1 = np.linalg.inv(a)
  b1 = np.linalg.inv(b)
  x = np.dot(a1,c)
  answer = np.around(np.dot(x, b1), 3)
  dic = {
  "task":task,
  "data": {"A": a.tolist(), "B": b.tolist(), "C": c.tolist()},
  "answer": answer.tolist()}
  return dic

print(GenerateSolveDoubleMatrixEquationTask())

{'task': 'Решите уравнение вида A·X·B = C. Ответ округлите до 3х знаков после запятой', 'data': {'A': [[-6, 1, -3], [-4, 1, -8], [-7, -2, 2]], 'B': [[-3, 9, -8], [-9, 6, 1], [-2, 6, 0]], 'C': [[-6, 4, 0], [-3, 4, 6], [-7, -5, 4]]}, 'answer': [[-0.023, -0.141, 0.151], [0.403, -0.095, -0.018], [0.152, 0.029, -0.266]]}


Ранг матрицы

In [94]:
def GenerateFindMatrixRankTask():
  switch = np.random.randint(0, 2, size=(1,1))[0][0]
  task = "Определите ранг матрицы"

  if switch == 0:
    matrix = np.random.randint(-9, 10, size=(3,3))
    answer = np.linalg.matrix_rank(matrix)
      
  else:
    matrix = np.random.randint(-9, 10, size=(2,3))
    factor1, factor2 = 0, 0
    while factor1 == 0 or factor2 == 0:
        factor1 = np.random.randint(-3, 4, size=(1,1))[0][0]
        factor2 = np.random.randint(-3, 4, size=(1,1))[0][0]

    matrix = np.vstack([matrix, factor1 * matrix[0] + factor2*matrix[1]])
    np.random.shuffle(matrix)
    answer = np.linalg.matrix_rank(matrix)
  
  dic = {
  "task":task,
  "data": matrix.tolist(),
  "answer": answer.item()}
  return dic

print(GenerateFindMatrixRankTask())

{'task': 'Определите ранг матрицы', 'data': [[-5, -9, -18], [-2, 3, 5], [-9, -3, -8]], 'answer': 2}


Система линейных уравнений

In [77]:
def generateSLU(x_count, equation_count, min_value, max_value):
  a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

  b = np.random.randint(min_value, max_value, size=(x_count, 1))
  x = np.random.randint(1, size=(x_count, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(min_value, max_value, size=(equation_count, x_count))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(min_value, max_value, size=(equation_count, x_count))

    b = np.random.randint(min_value, max_value, size=(x_count, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

print(generateSLU(3,3,-5, 21))

(array([[11,  0, -3],
       [ 3, 18, 16],
       [18,  2, -2]]), array([[ 7],
       [14],
       [11]]), array([[ 0.16504854],
       [ 2.28640777],
       [-1.72815534]]))


In [78]:
def GenerateSolveLinearEquationTask():
  a, b, x = generateSLU(3, 3, -5, 21)
  first_equation = f"{a[0][0]}*x + {a[0][1]}*y + {a[0][2]}*z = {b[0].item()}"
  second_equation = f"{a[1][0]}*x + {a[1][1]}*y + {a[1][2]}*z = {b[1].item()}"
  third_equation = f"{a[2][0]}*x + {a[2][1]}*y + {a[2][2]}*z = {b[2].item()}"
  task = "Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой"  
  answer = np.around(x,3).tolist()
  dic = {
  "task":task,
  "data": {"first_equation": first_equation, "second_equation": second_equation, "third_equation" : third_equation},
  "answer": answer}
  return dic

print(GenerateSolveLinearEquationTask())

{'task': 'Решите систему линейных уравнений. Ответ округлите до 3х знаков после запятой', 'data': {'first_equation': '7*x + 3*y + 15*z = 9', 'second_equation': '8*x + 13*y + 20*z = 20', 'third_equation': '-4*x + -2*y + 13*z = 13'}, 'answer': [[-0.864], [0.761], [0.851]]}


Скалярное произведение векторов

In [59]:
def GenerateScalarVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))
  task = "Вычислите скалярное произведение векторов A и B."
  answer = a * b
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0]},
    "answer": answer.tolist()[0]}
  return dic

print(GenerateScalarVectorMultiplicationTask())

{'task': 'Вычислите скалярное произведение векторов A и B.', 'data': {'A': [2, -11, -9], 'B': [4, 16, 10]}, 'answer': [8, -176, -90]}


Векторное произведение векторов

In [53]:
def GenerateVectorVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b])
  xy = combined[:2, :2]
  yz = combined[:2, 1:3]
  xz = combined[:2, [0, 2]]
  answer = np.array([int(np.linalg.det(yz)), -1 * int(np.linalg.det(xz)), int(np.linalg.det(xy))])
  task = "Вычислите векторное произведение векторов А и В."
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0]},
    "answer": answer.tolist()}
  return dic

print(GenerateVectorVectorMultiplicationTask())


{'task': 'Вычислите векторное произведение векторов А и В.', 'data': {'A': [15, -11, 2], 'B': [-4, -4, 1]}, 'answer': [-3, -23, -103]}


Длина Вектора

In [49]:

def GenerateVectorVectorMultiplicationModuleTask():
  temp = GenerateVectorVectorMultiplicationTask()
  a = temp["data"]["A"]
  b = temp["data"]["B"]
  vector = np.array(temp["answer"])
  answer = np.around(sqrt(vector[0]**2 + vector[1]**2 + vector[2]**2 ), 3)
  task = "Вычислите длинну вектора, полученную в результате векторного произведения A и B"
  dic = {
    "task": task,
    "data": {"A": a, "B": b},
    "answer": answer.tolist()}
  return dic


print(GenerateVectorVectorMultiplicationModuleTask())

{'task': 'Вычислите длинну вектора, полученную в результате векторного произведения A и B', 'data': {'A': [4, -6, 1], 'B': [5, -9, -15]}, 'answer': 118.038}


Смешанное произведение векторов

In [47]:
def GenerateMixedVectorMultiplicationTask():
  a = np.random.randint(-20, 21, size=(1,3))
  b = np.random.randint(-20, 21, size=(1,3))
  c = np.random.randint(-20, 21, size=(1,3))

  combined = np.vstack([a, b, c])
  answer = np.around(np.linalg.det(combined))
  task = "Вычислите смешанное произведение векторов A, B и C"
  dic = {
    "task": task,
    "data": {"A": a.tolist()[0], "B": b.tolist()[0], "C": c.tolist()[0]},
    "answer": answer}
  return dic

print(GenerateMixedVectorMultiplicationTask())


{'task': 'Вычислите смешанное произведение векторов A, B и C', 'data': {'A': [10, 11, -14], 'B': [-10, 8, 0], 'C': [14, 7, -18]}, 'answer': -872.0}
