In [1]:
import numpy as np
import sympy as sp
import scipy as sci

In [2]:
matrix_size = 3
matrix = np.random.randint(10, size=(matrix_size, matrix_size))
matrix

array([[5, 9, 4],
       [0, 0, 6],
       [1, 8, 4]])

конвертация матрицы в для отправки

In [3]:
dic = {"data": matrix.tolist()}
dic

{'data': [[5, 9, 4], [0, 0, 6], [1, 8, 4]]}

конвертация массива в матрицу

In [4]:
np.asmatrix(dic['data'])

matrix([[5, 9, 4],
        [0, 0, 6],
        [1, 8, 4]])

размер матрицы

In [5]:
matrix.shape == (matrix_size, matrix_size)

True

определитель

In [6]:
np.around(np.linalg.det(matrix), ), np.linalg.det(matrix)

(-186.0, -186.00000000000009)

транспонирование

In [7]:
matrix.transpose()

array([[5, 0, 1],
       [9, 0, 8],
       [4, 6, 4]])

Ранг матрицы

In [8]:
np.linalg.matrix_rank(matrix)

3

СЛУ

In [9]:
def generate_SLU():
  a = np.random.randint(-9, 10, size=(3, 3))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(-9, 10, size=(3,3))

  b = np.random.randint(1,10, size=(3, 1))
  x = np.random.randint(10, size=(3, 1))

  while((a.dot(x) != b).any()):
    a = np.random.randint(-9, 10, size=(3, 3))
    while (np.linalg.det(a) == 0):
      a = np.random.randint(-9, 10, size=(3,3))

    b = np.random.randint(1,10, size=(3, 1))
    x = np.linalg.solve(a, b)
  return (a,b,x)

In [10]:
%time
a,b,x = generate_SLU()

print("Матрица A:\n", a)
print("Вектор b:\n", b)
print("Решение системы:\n", x)
print("Решение системы:\n", np.around(x, 3))

print(a.dot(x) == b)

CPU times: total: 0 ns
Wall time: 0 ns
Матрица A:
 [[ 6 -6  2]
 [ 2 -6  4]
 [ 3  2  2]]
Вектор b:
 [[4]
 [5]
 [9]]
Решение системы:
 [[0.87096774]
 [0.9516129 ]
 [2.24193548]]
Решение системы:
 [[0.871]
 [0.952]
 [2.242]]
[[ True]
 [ True]
 [ True]]


обратная матрица

In [11]:
a = np.random.randint(-9, 10, size=(3,3))
while (np.linalg.det(a) == 0):
  a = np.random.randint(-9, 10, size=(3,3))
a

array([[-9, -3, -3],
       [-4,  2, -5],
       [ 6,  2, -2]])

In [12]:
InvA = np.around(np.linalg.inv(a), 3)
InvA

array([[ 0.05 , -0.1  ,  0.175],
       [-0.317,  0.3  , -0.275],
       [-0.167, -0.   , -0.25 ]])

Сумма матриц

In [13]:
matrix = np.random.randint(10, size=(4, 4))
row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
answer = matrix[row_index][column_index]
answer

7

Умножение числа на матрицу

In [14]:
matrix = np.random.randint(10, size=(4, 4))
number = np.random.randint(1, 10, size=(1,1))[0][0]

answer = matrix * number
answer

array([[72, 40, 24, 32],
       [72, 32, 32, 40],
       [48, 32, 72, 16],
       [72, 72, 48, 16]])

Умножение матриц

In [15]:
matrix1 = np.random.randint(-9, 10, size=(2,2))
matrix2 = np.random.randint(-9, 10, size=(2,2))


matrix1,matrix2,np.dot(matrix1, matrix2)

(array([[-2,  5],
        [ 7,  1]]),
 array([[ 7, -5],
        [ 3, -5]]),
 array([[  1, -15],
        [ 52, -40]]))

Генерация невырожденной матрицы

In [16]:
def generateNonsingularMatrix(min_value, max_value, rows_count, columns_count):
  a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))
  while (np.linalg.det(a) == 0):
    a = np.random.randint(min_value, max_value, size=(rows_count, columns_count))

  return a

Уравнение с определителем

In [17]:
matrix = generateNonsingularMatrix(-9, 10, 3, 3)
determinant = np.around(np.linalg.det(matrix))

row_count = matrix.shape[0]
columns_count = matrix.shape[1]

row_index = np.random.randint(0,row_count, size=(1,1))[0][0]
column_index = np.random.randint(0,columns_count, size=(1,1))[0][0]
random_elem = matrix[row_index][column_index]

new_matrix = np.where(matrix == random_elem, "x", matrix)

new_matrix, determinant, random_elem

(array([['8', 'x', '-3'],
        ['0', '-4', '-5'],
        ['-6', '1', '2']], dtype='<U11'),
 -162.0,
 -7)

Ранг матрицы

In [36]:
switch = np.random.randint(0, 2, size=(1,1))[0][0]
if switch == 0:
    matrix = np.random.randint(-9, 10, size=(3,3))

    print(matrix, np.linalg.matrix_rank(matrix))
else:
    matrix = np.random.randint(-9, 10, size=(2,3))
    factor1, factor2 = 0, 0
    while factor1 == 0 or factor2 == 0:
        factor1 = np.random.randint(-3, 4, size=(1,1))[0][0]
        factor2 = np.random.randint(-3, 4, size=(1,1))[0][0]

    matrix = np.vstack([matrix, factor1 * matrix[0] + factor2*matrix[1]])
    np.random.shuffle(matrix)

    print(matrix, factor1, factor2, np.linalg.matrix_rank(matrix))

[[  9  -3  -9]
 [-29  -5  21]
 [  1   7   3]] -3 -2 2
